### ISSUE TITLE
There is no token_reward in wordle train_bc file

### ISSUE THREAD

**Issue by ElegantLin** [Sea-Snell/Implicit-Language-Q-Learning#2]
Dear authors,

Thanks for your great job. However, when I try to run the` train_bc.py` in wordle file. I got the error that 

```
  File "/data2/xxx/Implicit-Language-Q-Learning/src/wordle/load_objects.py", line 99, in load_human_dataset
    token_reward = load_item(config['token_reward'], device, verbose=verbose)
KeyError: 'token_reward'
```

Could you please tell me more about the solution? 

I also have another question why we should run train_bc and get the weight first? Why cannot we train iql directly?

Thanks!

**Comment by Sea-Snell** [comment]
Ah apologies for the error!

I believe this issue can be fixed by changing:
```
model:
  transition_weight: 0.0
  dataset:
    name: wordle_human_dataset
    cache_id: d
  load:
    checkpoint_path: null
    strict_load: true
```

to:
```
model:
  transition_weight: 0.0
  dataset:
    name: wordle_human_dataset
    cache_id: d_train
  load:
    checkpoint_path: null
    strict_load: true
```

in `config/wordle/train_bc.yaml`


And as for why run bc first, of course you certainly can train IQL directly. But to run ILQL inference you need a BC model for the IQL value functions to perturb, which is why I recommend training BC first so that you can evaluate ILQL as it is training.

Thank you for the questions! Let me know if there is anything else I can help with!
